VERTICAL_TILE_COUNT = 16
HORIZONTAL_TILE_COUNT = 30
MINE_COUNT = 99
TILE_COUNT = VERTICAL_TILE_COUNT * HORIZONTAL_TILE_COUNT - MINE_COUNT
NUMBER_COUNT = 3

TILE_HEIGHT = TILE_WIDTH = 16
FACE_HEIGHT = FACE_WIDTH = 23
NUMBER_HEIGHT = 23
NUMBER_WIDTH = 13

HORIZONTAL_OFFSET = 1
VERTICAL_OFFSET = 2